# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1440612889);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1440613009);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1440612529);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1440612769);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1440612649);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 24);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.slowStartup.averageTime", 4796);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20150125222008");
user_pref("browser.startup.homepage_override.mstone", "35.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button-throttled\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":3,\"newElementCount\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1440698808443");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1440612471082");
user_pref("datareporting.policy.firstRunTime", "1440612408420");
user_pref("datareporting.sessions.current.activeTicks", 5);
user_pref("datareporting.sessions.current.firstPaint", 4605);
user_pref("datareporting.sessions.current.main", 567);
user_pref("datareporting.sessions.current.sessionRestored", 4336);
user_pref("datareporting.sessions.current.startTime", "1440613676786");
user_pref("datareporting.sessions.current.totalTime", 31);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1440612405643,\"a\":18,\"t\":146,\"c\":false,\"m\":609,\"fp\":5385,\"sr\":5313}");
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_TOOLBOX_OPENED_PER_USER_FLAG\":\"35.0.1\",\"DEVTOOLS_INSPECTOR_OPENED_PER_USER_FLAG\":\"35.0.1\",\"DEVTOOLS_RULEVIEW_OPENED_PER_USER_FLAG\":\"35.0.1\"}");
user_pref("devtools.toolbox.selectedTool", "inspector");
user_pref("devtools.toolsidebar-width.inspector", 0);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:35.0.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1440612889);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150402.01");
user_pref("extensions.lastAppVersion", "35.0.1");
user_pref("extensions.lastPlatformVersion", "35.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"40.0\",\"st\":1439981866000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"40.0\",\"st\":1439981866000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"35.0.1\",\"st\":1424288244000,\"mt\":1422226960000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"3.0\",\"st\":1424288290000,\"mt\":1420839872000}}}");
user_pref("gecko.buildID", "20150125222008");
user_pref("gecko.mstone", "35.0.1");
user_pref("idle.lastDailyNotification", 1440613569);
user_pref("loop.soft_start_ticket_number", 2333493);
user_pref("loop.throttled2", false);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1440612472);
user_pref("media.gmp-gmpopenh264.version", "1.3");
user_pref("media.gmp-manager.lastCheck", 1440612471);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.http.atsvc.enabled", false);
user_pref("network.http.atsvc.oe", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 101115);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1440613677);
user_pref("toolkit.telemetry.previousBuildID", "20150125222008");
